export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';

export const THEME_SWITCH = 'THEME_SWITCH';

export default {
  COUNTER_DECREMENT,
  COUNTER_INCREMENT,
  THEME_SWITCH,
};
